[tool.bumpversion]
current_version = "0.3.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "include/mitsuba/mitsuba.h"
parse = "#define ERD_MI_VERSION_MAJOR (?P<major>\\d+)\n#define ERD_MI_VERSION_MINOR (?P<minor>\\d+)\n#define ERD_MI_VERSION_PATCH (?P<patch>\\d+)\n"
serialize = ["#define ERD_MI_VERSION_MAJOR {major}\n#define ERD_MI_VERSION_MINOR {minor}\n#define ERD_MI_VERSION_PATCH {patch}\n"]
search = "{current_version}"
replace = "{new_version}"
